title: A New Era Has Arrived
author: Luis Villasenor
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mejorando el mundo un día a la vez.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
